"""empty message

Revision ID: a40ea796537e
Revises: 
Create Date: 2025-04-25 11:42:54.538761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40ea796537e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciudad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=True),
    sa.Column('pais', sa.String(length=40), nullable=True),
    sa.Column('temperatura', sa.Integer(), nullable=True),
    sa.Column('presion', sa.Integer(), nullable=True),
    sa.Column('humedad', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ciudad')
    # ### end Alembic commands ###
